### ISSUE TITLE
Remove -rs suffix for crate name

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spice-rs#28]
According to [rust naming guidelines](https://rust-lang.github.io/api-guidelines/naming.html) 

> Crate names should not use -rs or -rust as a suffix or prefix. Every crate is Rust! It serves no purpose to remind users of this constantly.

~For backward compatibility and to avoid breaking change it might be possible to keep old namespace/client `use spice_rs::Client` but mark it as deprecated/outdated.~

**Comment by sgrebnov** [comment]
Note: the package name (name under crates.io and dependencies section) and the crate/lib name (the name that dependencies will use to reference it) could be different, this is controlles by https://doc.rust-lang.org/cargo/reference/cargo-targets.html#the-name-field
```
[package]
name = "spice-rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "spice"
```
Then functionality is available as 
```
extern crate spice;

use spice::Client;
use spice::StreamExt;

```

**Comment by lukekim** [comment]
Renamed `spice_rs` -> `spiceai`
